# Generated by Django 4.1.6 on 2023-02-11 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_appointments'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='doctorname',
            field=models.CharField(default="<module 'datetime' from 'C:\\\\Users\\\\admin\\\\AppData\\\\Local\\\\Programs\\\\Python\\\\Python310\\\\lib\\\\datetime.py'>", max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointments',
            name='patientname',
            field=models.CharField(default="<module 'datetime' from 'C:\\\\Users\\\\admin\\\\AppData\\\\Local\\\\Programs\\\\Python\\\\Python310\\\\lib\\\\datetime.py'>", max_length=120),
            preserve_default=False,
        ),
    ]
