# Generated by Django 4.1.6 on 2023-02-11 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_appointments_doctorname_appointments_patientname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointments',
            name='doctorname',
        ),
    ]
