# Generated by Django 4.1.6 on 2023-02-12 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_appointments_doctorname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patientid', models.IntegerField()),
                ('doctorid', models.IntegerField()),
                ('medicinename', models.CharField(max_length=80)),
                ('quantity', models.CharField(max_length=80)),
                ('days', models.CharField(max_length=80)),
                ('time', models.CharField(max_length=80)),
            ],
        ),
        migrations.AddField(
            model_name='appointments',
            name='doctorurl',
            field=models.CharField(default="<module 'datetime' from 'C:\\\\Users\\\\admin\\\\AppData\\\\Local\\\\Programs\\\\Python\\\\Python310\\\\lib\\\\datetime.py'>", max_length=120),
            preserve_default=False,
        ),
    ]
