# Generated by Django 4.1.6 on 2023-02-12 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_medications_appointments_doctorurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='medications',
            name='doctorname',
            field=models.CharField(default="<module 'datetime' from 'C:\\\\Users\\\\admin\\\\AppData\\\\Local\\\\Programs\\\\Python\\\\Python310\\\\lib\\\\datetime.py'>", max_length=80),
            preserve_default=False,
        ),
    ]
