# Generated by Django 4.1.5 on 2023-01-18 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='products')),
                ('qualification', models.CharField(max_length=100)),
                ('details', models.TextField()),
                ('tags', models.CharField(max_length=100)),
                ('rating', models.IntegerField()),
                ('price_range', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=30)),
            ],
        ),
    ]
